import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header/HeaderComponent";
import {Provider} from "react-redux";
import {store} from "@/redux/store/store";
import StoreProvider from "@/app/storeProvider";
import ThemeProvider from "./ThemeProvider";
import Root from './Root'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

type PropType = {children: React.ReactNode;}
export default function RootLayout({
  children,
}: Readonly<PropType>) {
  return (
    <html lang="en">
      <StoreProvider>
          <ThemeProvider>
              <Root>
            <HeaderComponent/>
                  {children}
              </Root>
          </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
